name: Merge master to developer

on:
  release:
    branches: master
    types: [published, prereleased]

jobs:
  merge-to-dev:
    name: Merge back to develop
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'master'
          destination_branch: 'develop'
          pr_title: 'Merge ${{ github.ref}} back to develop'
          pr_reviewer: 'keith-cy'
          pr_label: 'auto-pr'
          github_token: ${{ secrets.GITHUB_TOKEN }}
